version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: leaderboard_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leaderboard_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    container_name: leaderboard_redis
    restart: always
    command: [
      "redis-server",
      "--requirepass", "redis1234",
      "--appendonly", "yes"
    ]
    ports:
      - "6379:6379"

volumes:
  pgdata:
